# This file can be used to install module dependencies for unit  for details
---
fixtures:
  forge_modules:
    apt:
      repo: 'puppetlabs/apt'
      ref: '7.3.0'
    stdlib:
      repo: 'puppetlabs/stdlib'
      ref: '5.2.0'
    translate:
      repo: 'puppetlabs/translate'
      ref: '2.1.0'
    concat:
      repo: 'puppetlabs/concat'
      ref: '6.2.0'
